import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Briefcase, Plus, MapPin, Users, Clock, Edit, Eye, Bot, X, Sparkles } from 'lucide-react';
import { chatWithGemini } from '@/services/gemini';
import toast from 'react-hot-toast';
import clsx from 'clsx';

const JOBS = [
  { id:1, title:'Senior Full Stack Developer', dept:'Engineering', location:'New York / Remote', type:'Full-Time', mode:'Hybrid',  openings:2, applications:14, status:'open',   posted:'Dec 1',  closing:'Dec 31', skills:['React','Node.js','MongoDB','AWS'] },
  { id:2, title:'Product Manager',             dept:'Product',     location:'San Francisco',    type:'Full-Time', mode:'Office',  openings:1, applications:9,  status:'open',   posted:'Dec 3',  closing:'Dec 24', skills:['Agile','Jira','OKRs','Figma']   },
  { id:3, title:'HR Generalist',               dept:'HR',          location:'Austin, TX',       type:'Full-Time', mode:'Office',  openings:1, applications:22, status:'open',   posted:'Dec 5',  closing:'Dec 20', skills:['Recruitment','HRIS','Compliance'] },
  { id:4, title:'Sales Development Rep',       dept:'Sales',       location:'Chicago',          type:'Full-Time', mode:'Hybrid',  openings:3, applications:31, status:'open',   posted:'Nov 28', closing:'Jan 15', skills:['Salesforce','B2B Sales','CRM']   },
  { id:5, title:'DevOps Engineer',             dept:'Engineering', location:'Remote',           type:'Full-Time', mode:'Remote',  openings:1, applications:7,  status:'open',   posted:'Nov 20', closing:'Feb 1',  skills:['Docker','Kubernetes','AWS']      },
  { id:6, title:'UI/UX Designer',              dept:'Design',      location:'New York',         type:'Full-Time', mode:'Hybrid',  openings:1, applications:18, status:'closed', posted:'Nov 1',  closing:'Dec 1',  skills:['Figma','Prototyping','Research']  },
];

const STATUS_COLORS = { open:'badge-success', closed:'badge-danger', draft:'badge-neutral', on_hold:'badge-warning' };
const MODE_COLORS   = { Remote:'text-primary-400', Hybrid:'text-warning-400', Office:'text-slate-400' };

export default function JobListings() {
  const [jobs, setJobs]             = useState(JOBS);
  const [showAdd, setShowAdd]       = useState(false);
  const [generating, setGenerating] = useState(false);
  const [form, setForm]             = useState({ title:'', dept:'Engineering', location:'', type:'Full-Time', mode:'Hybrid', openings:1, closing:'', skills:'' });
  const [generatedJD, setGeneratedJD] = useState(null);

  const handleGenerateJD = async () => {
    if (!form.title) { toast.error('Enter a job title first'); return; }
    setGenerating(true);
    try {
      const prompt = `Generate a concise job description for a "${form.title}" role in ${form.dept} department.
Return ONLY valid JSON with these fields:
{"description":"2 paragraph description","responsibilities":["item1","item2","item3","item4","item5"],"requirements":["item1","item2","item3","item4"],"skills":["skill1","skill2","skill3","skill4","skill5"]}`;

      const messages = [{ role:'user', content: prompt }];
      const reply = await chatWithGemini(messages, { role:'hr_recruiter' });
      const clean = reply.replace(/```json|```/gi,'').trim();
      const parsed = JSON.parse(clean);
      setGeneratedJD(parsed);
      if (parsed.skills) setForm(f => ({...f, skills: parsed.skills.join(', ')}));
      toast.success('Job description generated by Gemini AI!');
    } catch(e) {
      toast.error('AI generation failed — check your VITE_GEMINI_API_KEY');
    } finally {
      setGenerating(false);
    }
  };

  const handleSubmit = () => {
    const newJob = {
      id: jobs.length + 1, ...form,
      openings: +form.openings, applications: 0, status:'open',
      posted: new Date().toLocaleDateString('en-US',{month:'short',day:'numeric'}),
      skills: form.skills.split(',').map(s=>s.trim()).filter(Boolean),
    };
    setJobs(prev => [newJob, ...prev]);
    setShowAdd(false);
    setGeneratedJD(null);
    setForm({ title:'', dept:'Engineering', location:'', type:'Full-Time', mode:'Hybrid', openings:1, closing:'', skills:'' });
    toast.success('Job posted successfully!');
  };

  return (
    <div className="space-y-5">
      <motion.div initial={{opacity:0,y:-10}} animate={{opacity:1,y:0}} className="flex-between flex-wrap gap-3">
        <div>
          <h1 className="font-display text-2xl font-bold text-white">Job Listings</h1>
          <p className="text-slate-400 text-sm mt-0.5">{jobs.filter(j=>j.status==='open').length} open positions · {jobs.reduce((s,j)=>s+j.applications,0)} total applications</p>
        </div>
        <button onClick={()=>setShowAdd(true)} className="btn-primary text-xs">
          <Plus className="w-3.5 h-3.5"/>Post New Job
        </button>
      </motion.div>

      {/* Job cards */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {jobs.map((job,i) => (
          <motion.div key={job.id} initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{delay:i*0.06}}
            className="glass-card-hover p-5">
            <div className="flex-between mb-3">
              <div className="flex items-center gap-2.5">
                <div className="w-9 h-9 rounded-xl bg-primary-500/10 flex-center">
                  <Briefcase className="w-4.5 h-4.5 text-primary-400" size={18}/>
                </div>
                <div>
                  <p className="text-sm font-semibold text-white">{job.title}</p>
                  <p className="text-[10px] text-slate-500">{job.dept}</p>
                </div>
              </div>
              <span className={clsx('badge text-[10px]', STATUS_COLORS[job.status])}>{job.status}</span>
            </div>

            <div className="flex flex-wrap gap-3 text-xs text-slate-400 mb-3">
              <span className="flex items-center gap-1"><MapPin className="w-3 h-3"/>{job.location}</span>
              <span className="flex items-center gap-1"><Clock className="w-3 h-3"/>Closes {job.closing}</span>
              <span className={clsx('flex items-center gap-1', MODE_COLORS[job.mode]||'text-slate-400')}>● {job.mode}</span>
            </div>

            <div className="flex flex-wrap gap-1.5 mb-3">
              {job.skills?.slice(0,4).map(s => (
                <span key={s} className="text-[10px] text-slate-400 bg-white/5 border border-white/10 px-2 py-0.5 rounded-full">{s}</span>
              ))}
            </div>

            <div className="flex-between pt-3 border-t border-white/5">
              <div className="flex items-center gap-3 text-xs text-slate-500">
                <span className="flex items-center gap-1"><Users className="w-3 h-3"/>{job.applications} applied</span>
                <span>{job.openings} opening{job.openings>1?'s':''}</span>
              </div>
              <div className="flex gap-1.5">
                <button className="btn-ghost p-1.5"><Eye className="w-3.5 h-3.5"/></button>
                <button className="btn-ghost p-1.5"><Edit className="w-3.5 h-3.5"/></button>
              </div>
            </div>
          </motion.div>
        ))}
      </div>

      {/* Add Job Modal */}
      <AnimatePresence>
        {showAdd && (
          <div className="fixed inset-0 bg-black/60 z-50 flex-center p-4 overflow-y-auto" onClick={()=>setShowAdd(false)}>
            <motion.div initial={{opacity:0,scale:0.95}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:0.95}}
              className="bg-surface-900 border border-white/10 rounded-2xl w-full max-w-2xl p-6 my-4"
              onClick={e=>e.stopPropagation()}>
              <div className="flex-between mb-5">
                <h3 className="font-display font-bold text-white text-lg">Post New Job</h3>
                <button onClick={()=>setShowAdd(false)} className="text-slate-400 hover:text-white"><X className="w-5 h-5"/></button>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-4">
                <div className="sm:col-span-2">
                  <label className="input-label">Job Title *</label>
                  <div className="flex gap-2">
                    <input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}
                      placeholder="e.g. Senior React Developer" className="input-field text-sm flex-1"/>
                    <button onClick={handleGenerateJD} disabled={generating}
                      className="btn-primary text-xs flex-shrink-0 whitespace-nowrap">
                      {generating
                        ? <><div className="w-3.5 h-3.5 border-2 border-white/30 border-t-white rounded-full animate-spin"/>Generating...</>
                        : <><Sparkles className="w-3.5 h-3.5"/>AI Generate</>}
                    </button>
                  </div>
                </div>
                {[
                  { label:'Department', key:'dept',     type:'select', opts:['Engineering','HR','Sales','Marketing','Finance','Product','Design','Operations'] },
                  { label:'Location',   key:'location', type:'text',   placeholder:'New York / Remote' },
                  { label:'Job Type',   key:'type',     type:'select', opts:['Full-Time','Part-Time','Contract','Intern'] },
                  { label:'Work Mode',  key:'mode',     type:'select', opts:['Office','Remote','Hybrid'] },
                  { label:'Openings',   key:'openings', type:'number', placeholder:'1' },
                  { label:'Closing Date',key:'closing', type:'date' },
                ].map(f => (
                  <div key={f.key}>
                    <label className="input-label">{f.label}</label>
                    {f.type==='select'
                      ? <select value={form[f.key]} onChange={e=>setForm({...form,[f.key]:e.target.value})} className="input-field text-sm">
                          {f.opts.map(o=><option key={o}>{o}</option>)}
                        </select>
                      : <input type={f.type} value={form[f.key]} placeholder={f.placeholder}
                          onChange={e=>setForm({...form,[f.key]:e.target.value})} className="input-field text-sm"/>
                    }
                  </div>
                ))}
                <div className="sm:col-span-2">
                  <label className="input-label">Required Skills (comma-separated)</label>
                  <input value={form.skills} onChange={e=>setForm({...form,skills:e.target.value})}
                    placeholder="React, Node.js, MongoDB..." className="input-field text-sm"/>
                </div>
              </div>

              {/* AI Generated JD preview */}
              {generatedJD && (
                <div className="mb-4 p-4 bg-primary-500/10 border border-primary-500/20 rounded-xl">
                  <div className="flex items-center gap-2 mb-2">
                    <Bot className="w-4 h-4 text-primary-400"/>
                    <span className="text-xs font-semibold text-primary-300">Gemini AI Generated JD</span>
                  </div>
                  <p className="text-xs text-slate-300 leading-relaxed mb-2">{generatedJD.description}</p>
                  <div className="grid grid-cols-2 gap-3 text-xs">
                    <div>
                      <p className="text-[10px] text-slate-500 uppercase font-semibold mb-1">Responsibilities</p>
                      {generatedJD.responsibilities?.slice(0,3).map((r,i)=><p key={i} className="text-slate-400 mb-0.5">• {r}</p>)}
                    </div>
                    <div>
                      <p className="text-[10px] text-slate-500 uppercase font-semibold mb-1">Requirements</p>
                      {generatedJD.requirements?.slice(0,3).map((r,i)=><p key={i} className="text-slate-400 mb-0.5">• {r}</p>)}
                    </div>
                  </div>
                </div>
              )}

              <div className="flex gap-2">
                <button onClick={()=>setShowAdd(false)} className="btn-secondary flex-1 justify-center text-xs">Cancel</button>
                <button onClick={handleSubmit} className="btn-primary flex-1 justify-center text-xs">
                  <Plus className="w-3.5 h-3.5"/>Post Job
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
